In [1]:
conda install numpy

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


# Section 5: Python for Data Analysis 

## 18. Numpy Arrays 

In [2]:
mylist = [1,2,3]

In [3]:
import numpy as np

In [5]:
arr = np.array(mylist)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
# Create arrays that contains even numbers from 0 to 10
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
# If we want specific types of arrays
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# linspace, still one dimensional becuase there is only one bracket[]
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
# Call random numbers: 1 dimensional 
np.random.rand(5)

array([0.07477991, 0.5512722 , 0.56214362, 0.69598257, 0.84823114])

In [21]:
# Call random numbers: 2 dimensional 
np.random.rand(5,5)

array([[0.27149788, 0.52131782, 0.7076307 , 0.17434384, 0.06637047],
       [0.63589552, 0.94249802, 0.87147359, 0.97965232, 0.9960583 ],
       [0.86987616, 0.39573316, 0.41052537, 0.58607991, 0.30339645],
       [0.02867826, 0.15841337, 0.57881921, 0.93478371, 0.69067108],
       [0.52714117, 0.82283836, 0.4567719 , 0.38119321, 0.74614872]])

In [23]:
# Call random number from standard normal distribution 
np.random.randn(4,4)

array([[ 0.82176162, -0.74578651,  0.35292033,  0.81925983],
       [ 1.13613145, -1.79637891,  1.44791865,  2.03769493],
       [-1.29585194, -1.13555792, -1.99600899,  2.12418831],
       [-0.98476243,  0.19982274,  0.31266038,  0.00902422]])

In [28]:
# Return random intergers from a low to a high number 
np.random.randint(1,100,10) # we pick 10 numbers 

array([12, 82, 86, 67, 13, 78, 65, 71, 91, 47])

In [30]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
# Reshape method 
arr.reshape(5,5) #reshape it as a 5 by 5 array -2 dimensional
                 #number of rows * number of columns = total number 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr = np.random.randint(0,50,10)
ranarr

array([38, 15, 35, 47, 11, 12, 38,  4, 37, 43])

In [39]:
# Call max number 
ranarr.max()

47

In [40]:
ranarr.min()

4

In [41]:
ranarr.argmax() # index = 3 has maximum value 

3

In [43]:
ranarr.argmin()

7

In [44]:
# data type of array 
arr.dtype

dtype('int64')

## 20. Numpy Array indexing

In [48]:
import numpy as np

In [59]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[8]

8

In [53]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [55]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr[0:5] = 100

In [58]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [60]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [63]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [65]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr_copy[:]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
# two general formats for grabbing elements 

arr_2d[1][1]   # first method 

25

In [73]:
arr_2d[1,2]

30

In [74]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [75]:
# Conditional selection 

arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [81]:
arr[bool_arr]        # only grab array that is True 

array([ 6,  7,  8,  9, 10])

In [82]:
arr_2d = np.arange(50).reshape(5,10)

In [86]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [87]:
arr_2d[1:3,2:4]

array([[12, 13],
       [22, 23]])

## 21. Numpy Operations

In [88]:
import numpy as np

In [89]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
# we can add arrays together, or times 
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [91]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [93]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [94]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [95]:
# square root everything in array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [96]:
np.random.randint(0,50,10)

array([42, 14,  5, 48, 15,  2, 23, 40, 37, 27])

In [97]:
np.random.rand(0,1,1)

array([], shape=(0, 1, 1), dtype=float64)

In [98]:
np.random.rand(5,5)

array([[0.4955787 , 0.36026018, 0.50358005, 0.83561605, 0.7842266 ],
       [0.23534339, 0.16500473, 0.36651   , 0.97729434, 0.72531815],
       [0.8318487 , 0.2537747 , 0.02310274, 0.03850608, 0.98183889],
       [0.69094148, 0.89665235, 0.15662238, 0.55786083, 0.83390583],
       [0.71781985, 0.17753431, 0.54528361, 0.14926008, 0.8253913 ]])

# Section 6. Python for data analysis - pandas

In [102]:
conda install pandas

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


## 26. Series

In [103]:
import numpy as np

In [104]:
import pandas as pd

In [106]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [108]:
# create a series 
# the key to panda series is that we can specify what you want that index to be. 
pd.Series(data = my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [110]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [111]:
# we also can pass a dictionary 
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [113]:
# we also could pass built-in function 
pd.Series(data=[sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [114]:
# Grab information from Series 
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])

In [115]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [117]:
ser2 = pd.Series([1,2,5,4],['USA','Germany','Italy','Japan'])

In [118]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [119]:
ser1['USA']

1

In [124]:
ser1 +ser2   # dtype change to float 

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

## 27. DatafFrames 

In [134]:
from numpy.random import randn

In [132]:
np.random.seed(101)

In [136]:
# create dataframe, df is just a bunch of series that share the same index
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [137]:
# return W column - a series 
df['W']

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: W, dtype: float64

In [138]:
type(df['W'])

pandas.core.series.Series

In [157]:
df[['W','Z']] # return 2 columns, need use double bracket 

W         Z
A -0.993263  0.000366
B  1.025984  0.649826
C  2.154846 -0.346419
D  0.147027  1.024810
E -0.925874  0.610478

In [143]:
# add a new column 
df['new'] = df['W'] + df['Y']
df

W         X         Y         Z       new
A -0.993263  0.196800 -1.136645  0.000366 -2.129908
B  1.025984 -0.156598 -0.031579  0.649826  0.994405
C  2.154846 -0.610259 -0.755325 -0.346419  1.399521
D  0.147027 -0.479448  0.558769  1.024810  0.705796
E -0.925874  1.862864 -1.133817  0.610478 -2.059691

In [153]:
# delete a new column 
df.drop('new', axis = 1, inplace=True) # inplace = True: if we want our  
                                       # changes stay(改变原本的df)
# axis = 1 means column, axis=0 means row 

In [159]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [155]:
df.drop('E', axis = 0)

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [158]:
df.shape

(5, 4)

In [160]:
# Select rows 
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [161]:
df.loc['A']

W   -0.993263
X    0.196800
Y   -1.136645
Z    0.000366
Name: A, dtype: float64

In [162]:
df.iloc[0]

W   -0.993263
X    0.196800
Y   -1.136645
Z    0.000366
Name: A, dtype: float64

In [165]:
# select subsets of rows and columns 
df.loc['A','W']

-0.993263499973366

In [166]:
df.loc[['A','B'],['W','Y']]

W         Y
A -0.993263 -1.136645
B  1.025984 -0.031579

In [167]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [170]:
booldf = df>0
booldf

W      X      Y      Z
A  False   True  False   True
B   True  False  False   True
C   True  False  False  False
D   True  False   True   True
E  False   True  False   True

In [171]:
# return values where it is true, NaN means false 
df[booldf]

W         X         Y         Z
A       NaN  0.196800       NaN  0.000366
B  1.025984       NaN       NaN  0.649826
C  2.154846       NaN       NaN       NaN
D  0.147027       NaN  0.558769  1.024810
E       NaN  1.862864       NaN  0.610478

In [172]:
df[df>0]

W         X         Y         Z
A       NaN  0.196800       NaN  0.000366
B  1.025984       NaN       NaN  0.649826
C  2.154846       NaN       NaN       NaN
D  0.147027       NaN  0.558769  1.024810
E       NaN  1.862864       NaN  0.610478

In [175]:
df[df['W']>0]

W         X         Y         Z
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [183]:
resultdf = df[df['Z']<0]
resultdf 

W         X         Y         Z
C  2.154846 -0.610259 -0.755325 -0.346419

In [184]:
resultdf['X']

C   -0.610259
Name: X, dtype: float64

In [188]:
df[df['Z']<0][['Y','X']]

Y         X
C -0.755325 -0.610259

In [189]:
# multiple conditions
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [191]:
df[ (df['W']>0) and (df['Y']>1) ]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [196]:
df[ (df['W']>1) & (df['X']<0) ]

W         X         Y         Z
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419

In [197]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [198]:
df.reset_index()

index         W         X         Y         Z
0     A -0.993263  0.196800 -1.136645  0.000366
1     B  1.025984 -0.156598 -0.031579  0.649826
2     C  2.154846 -0.610259 -0.755325 -0.346419
3     D  0.147027 -0.479448  0.558769  1.024810
4     E -0.925874  1.862864 -1.133817  0.610478

In [200]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [201]:
df['States'] = newind

In [202]:
df

W         X         Y         Z States
A -0.993263  0.196800 -1.136645  0.000366     CA
B  1.025984 -0.156598 -0.031579  0.649826     NY
C  2.154846 -0.610259 -0.755325 -0.346419     WY
D  0.147027 -0.479448  0.558769  1.024810     OR
E -0.925874  1.862864 -1.133817  0.610478     CO

In [203]:
df.set_index('States')

W         X         Y         Z
States                                        
CA     -0.993263  0.196800 -1.136645  0.000366
NY      1.025984 -0.156598 -0.031579  0.649826
WY      2.154846 -0.610259 -0.755325 -0.346419
OR      0.147027 -0.479448  0.558769  1.024810
CO     -0.925874  1.862864 -1.133817  0.610478

In [204]:
# multi-level index 
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [207]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [210]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])
df

A         B
G1 1  0.392489  0.221491
   2 -0.855196  1.541990
   3  0.666319 -0.538235
G2 1 -0.568581  1.407338
   2  0.641806 -0.905100
   3 -0.391157  1.028293

In [215]:
df.loc['G1']['A']

1    0.392489
2   -0.855196
3    0.666319
Name: A, dtype: float64

In [217]:
df.index.names = 'Groups','Num'
df

A         B
Groups Num                    
G1     1    0.392489  0.221491
       2   -0.855196  1.541990
       3    0.666319 -0.538235
G2     1   -0.568581  1.407338
       2    0.641806 -0.905100
       3   -0.391157  1.028293

In [221]:
df.loc['G2']['B'][2]

-0.905099901810439

In [224]:
df.loc['G2'].loc[2]['B']

-0.905099901810439

In [225]:
# cross section
df.xs('G1')

A         B
Num                    
1    0.392489  0.221491
2   -0.855196  1.541990
3    0.666319 -0.538235

In [226]:
df.xs(1,level='Num')

A         B
Groups                    
G1      0.392489  0.221491
G2     -0.568581  1.407338

## 30. Missing Data

In [227]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [229]:
df = pd.DataFrame(d)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [232]:
df.dropna(axis=0) # drop any row with missing values 

A    B  C
0  1.0  5.0  1

In [233]:
df.dropna(axis=1) # drop any columns with missing values 

C
0  1
1  2
2  3

In [234]:
df.dropna(thresh=2) # keep if there are less than 2 missing values in a row

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [235]:
df.fillna(value='Fill value')

A           B  C
0           1           5  1
1           2  Fill value  2
2  Fill value  Fill value  3

In [236]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

## 31. Groupby

In [237]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [239]:
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [244]:
# Groupby company 
byCompany = df.groupby('Company')
byCompany.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [247]:
byCompany.sum().loc['FB'] # sales sum of FB 


Sales    593
Name: FB, dtype: int64

In [248]:
df.groupby('Company').sum().loc['FB'] # write in one line 

Sales    593
Name: FB, dtype: int64

In [249]:
df.groupby('Company').max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [250]:
df.groupby('Company').describe() 

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

## 32. Operations

In [262]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],
                   'col2':[444,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [253]:
# fine unique values - 3 method 
df['col2'].unique()

array([444, 555, 666])

In [254]:
# number of unique values 
df['col2'].nunique()

3

In [255]:
# how many times each unique value occurs
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [256]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [258]:
df[(df['col1']>2) & (df['col2']==444)]

col1  col2 col3
3     4   444  xyz

In [259]:
# apply method to apply function 
def times2(x):
    return x*2

In [260]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [261]:
# apply function is powerful when we combine own-customized lambda 
df['col2'].apply(lambda x:x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [263]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [264]:
df.drop('col1', axis=1)

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [265]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [266]:
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [267]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [268]:
# pivot table 
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [271]:
df.pivot_table(values='D',index=['A','B'], columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

## 34. Data input and output

In [272]:
conda install sqlalchemy

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [273]:
conda install lxml

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [274]:
conda install html5lib 

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [275]:
conda install BeatifulSoup4

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - beatifulsoup4

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



Note: you may need to restart the kernel to use updated packages.
